{{- if .Values.prowlarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-stack.appFullname" (dict "root" . "app" "prowlarr") }}
  labels:
    {{- include "media-stack.appLabels" (dict "root" . "app" "prowlarr") | nindent 4 }}
spec:
  type: {{ .Values.prowlarr.service.type }}
  ports:
    - port: {{ .Values.prowlarr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "media-stack.appSelectorLabels" (dict "root" . "app" "prowlarr") | nindent 4 }}
{{- end }}
