{{- if .Values.prowlarr.enabled }}
{{- if .Values.prowlarr.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "media-stack.serviceAccountName" (dict "root" . "app" "prowlarr") }}
  labels:
    {{- include "media-stack.appLabels" (dict "root" . "app" "prowlarr") | nindent 4 }}
  {{- with .Values.prowlarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
