{{- if .Values.tdarrNode.enabled }}
{{- if .Values.tdarrNode.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-tdarr-node" (include "media-stack.fullname" .)) .Values.tdarrNode.serviceAccount.name }}
  labels:
    {{- include "media-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: tdarr-node
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tdarr-node
  {{- with .Values.tdarrNode.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
