{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarr.fullname" . }}-config
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    {{- include "sonarr.commonAnnotations" . | nindent 4 }}
    {{- with .Values.persistence.config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- include "sonarr.storageClassName" .Values.persistence.config | nindent 2 }}
{{- end }}
---
{{- if and .Values.persistence.tv.enabled (not .Values.persistence.tv.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarr.fullname" . }}-tv
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    {{- include "sonarr.commonAnnotations" . | nindent 4 }}
    {{- with .Values.persistence.tv.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.tv.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.tv.size }}
  {{- include "sonarr.storageClassName" .Values.persistence.tv | nindent 2 }}
{{- end }}
---
{{- if and .Values.persistence.downloads.enabled (not .Values.persistence.downloads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarr.fullname" . }}-downloads
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    {{- include "sonarr.commonAnnotations" . | nindent 4 }}
    {{- with .Values.persistence.downloads.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}
  {{- include "sonarr.storageClassName" .Values.persistence.downloads | nindent 2 }}
{{- end }}