{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sonarr.serviceAccountName" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    {{- include "sonarr.commonAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}